// Ash compiler — C code generator
// Multi-return functions: a Ash function returning (T1, T2, ...) gets a
// companion C struct  __Ash_<FuncName>_ret  and returns it by value.
// At the call site  x, y := f()  is lowered to:
//   __Ash_f_ret __tmp = ash_f(...);
//   T1 x = __tmp._0;
//   T2 y = __tmp._1;

const std = @import("std");
const ast = @import("ast.zig");

const Node      = ast.Node;
const NodeKind  = ast.NodeKind;
const AshType   = ast.AshType;
const TypeKind  = ast.TypeKind;
const BinaryOp  = ast.BinaryOp;
const CompoundOp = ast.CompoundOp;

pub const CodegenError = error{ OutOfMemory, IoError };

pub const Codegen = struct {
    allocator:          std.mem.Allocator,
    out:                std.ArrayListUnmanaged(u8),
    indent:             usize,
    cur_func_ret_struct: []const u8, // set when entering a multi-return function

    pub fn init(a: std.mem.Allocator) Codegen {
        return .{ .allocator = a, .out = .{}, .indent = 0, .cur_func_ret_struct = "" };
    }
    pub fn deinit(self: *Codegen) void { self.out.deinit(self.allocator); }
    pub fn result(self: *Codegen) []const u8 { return self.out.items; }

    fn w(self: *Codegen, s: []const u8) CodegenError!void {
        self.out.appendSlice(self.allocator, s) catch return CodegenError.OutOfMemory;
    }
    fn wf(self: *Codegen, comptime fmt: []const u8, args: anytype) CodegenError!void {
        std.fmt.format(self.out.writer(self.allocator), fmt, args)
            catch return CodegenError.OutOfMemory;
    }
    fn ind(self: *Codegen) CodegenError!void {
        var i: usize = 0;
        while (i < self.indent) : (i += 1) try self.w("    ");
    }

    // ── C type helpers ─────────────────────────────────────────────────────

    // cTypeOf returns a string slice valid for this call (static or comptime literal)
    fn cTypeOf(_: *Codegen, t: AshType) []const u8 {
        return switch (t.kind) {
            .Int    => "int64_t",
            .Float  => "double",
            .Bool   => "int",
            .String => "const char*",
            .Void   => "void",
            .Vec    => "AshVec*",
            .Struct => "void*",   // overridden where struct name is known
            .Enum   => "int64_t",
            .Tuple  => "void*",   // never used directly; handled via ret-struct
            .Unknown => "void*",
            .Array  => "void*",   // overridden by cTypeOfArray
        };
    }

    fn cTypeOfArray(_: *Codegen, t: AshType) []const u8 {
        const et = if (t.elem_type) |e| e.* else AshType{ .kind = .Unknown };
        return switch (et.kind) {
            .Int    => "int64_t*",
            .Float  => "double*",
            .Bool   => "int*",
            .String => "const char**",
            else    => "void*",
        };
    }

    // Emit a C type for a param/var that might be a named struct or array
    fn emitCType(self: *Codegen, t: AshType) CodegenError!void {
        switch (t.kind) {
            .Struct => try self.w(t.name orelse "void*"),
            .Array  => try self.w(self.cTypeOfArray(t)),
            else    => try self.w(self.cTypeOf(t)),
        }
    }

    // Name of the C return-struct for a multi-return function
    fn retStructName(self: *Codegen, func_name: []const u8) CodegenError![]u8 {
        return std.fmt.allocPrint(self.allocator, "__Ash_{s}_ret", .{func_name});
    }

    // ── top-level ──────────────────────────────────────────────────────────

    pub fn generate(self: *Codegen, program: *Node) CodegenError!void {
        try self.w("/* Generated by Ash compiler */\n");
        try self.w("#include <stdint.h>\n");
        try self.w("#include <string.h>\n");
        try self.w("#include <stddef.h>\n");
        try self.w("#include \"ash_runtime.h\"\n\n");

        const pd = &program.data.program;

        // 1. Emit struct type declarations (user-defined structs)
        for (pd.structs) |s| try self.emitStructTypeDecl(s);

        // 2. Emit enum constants as C #defines
        for (pd.enums) |e| try self.emitEnumDefines(e);

        // 3. Emit multi-return helper structs for functions that return tuples
        for (pd.functions) |func| try self.emitReturnStructIfNeeded(func);

        // 4. Forward-declare all user functions so any order works
        for (pd.functions) |func| try self.emitFunctionSignature(func, true);
        try self.w("\n");

        // 5. Full function bodies
        for (pd.functions) |func| try self.emitFunctionBody(func);

        // 5. C main
        try self.w("int main(int argc, char** argv) {\n");
        try self.w("    ash_os_init(argc, argv);\n");
        try self.w("    ash_main();\n");
        try self.w("    return 0;\n");
        try self.w("}\n");
    }

    fn emitStructTypeDecl(self: *Codegen, s: *Node) CodegenError!void {
        const sd = &s.data.struct_decl;
        try self.wf("typedef struct {{\n", .{});
        for (sd.fields) |f| {
            const ct: []const u8 = switch (f.field_type.kind) {
                .Int    => "int64_t",
                .Float  => "double",
                .Bool   => "int",
                .String => "const char*",
                .Vec    => "AshVec*",
                else    => "void*",
            };
            try self.wf("    {s} {s};\n", .{ ct, f.name });
        }
        try self.wf("}} {s};\n\n", .{sd.name});
    }

    fn emitEnumDefines(self: *Codegen, e: *Node) CodegenError!void {
        const ed = &e.data.enum_decl;
        for (ed.variants, 0..) |v, i| {
            try self.wf("#define ASH_{s}__{s} INT64_C({d})\n", .{ ed.name, v, i });
        }
        try self.w("\n");
    }

    fn emitReturnStructIfNeeded(self: *Codegen, func: *Node) CodegenError!void {
        const fd = &func.data.function_decl;
        const rt = fd.return_type orelse return;
        if (rt.kind != .Tuple) return;
        const tt = rt.tuple_types orelse return;
        const sname = try self.retStructName(fd.name);
        defer self.allocator.free(sname);
        try self.wf("typedef struct {{\n", .{});
        for (tt, 0..) |member, i| {
            try self.w("    ");
            try self.emitCType(member);
            try self.wf(" _{d};\n", .{i});
        }
        try self.wf("}} {s};\n\n", .{sname});
    }

    // Emit just the signature (with or without trailing semicolon)
    fn emitFunctionSignature(self: *Codegen, func: *Node, forward: bool) CodegenError!void {
        const fd = &func.data.function_decl;
        const rt = fd.return_type orelse AshType{ .kind = .Void };

        // Return type
        if (rt.kind == .Tuple) {
            const sname = try self.retStructName(fd.name);
            defer self.allocator.free(sname);
            try self.wf("{s}", .{sname});
        } else {
            try self.emitCType(rt);
        }
        try self.wf(" ash_{s}(", .{fd.name});

        // Parameters
        for (fd.params, 0..) |p, i| {
            if (i > 0) try self.w(", ");
            const pd2 = &p.data.param_decl;
            if (pd2.param_type.kind == .Struct) {
                try self.w(pd2.param_type.name orelse "void*");
            } else {
                try self.emitCType(pd2.param_type);
            }
            try self.wf(" {s}", .{pd2.name});
        }

        if (forward) try self.w(");\n") else try self.w(") ");
    }

    fn emitFunctionBody(self: *Codegen, func: *Node) CodegenError!void {
        const fd = &func.data.function_decl;
        const rt = fd.return_type orelse AshType{ .kind = .Void };
        if (rt.kind == .Tuple) {
            self.cur_func_ret_struct = try self.retStructName(fd.name);
        } else {
            self.cur_func_ret_struct = "";
        }
        try self.emitFunctionSignature(func, false);
        try self.w("{\n");
        self.indent += 1;
        try self.genBlock(fd.body);
        self.indent -= 1;
        try self.w("}\n\n");
        if (rt.kind == .Tuple) {
            self.allocator.free(self.cur_func_ret_struct);
            self.cur_func_ret_struct = "";
        }
    }

    // ── statements ─────────────────────────────────────────────────────────

    fn genBlock(self: *Codegen, block: *Node) CodegenError!void {
        for (block.data.block.stmts) |s| try self.genStmt(s);
    }

    fn genStmt(self: *Codegen, stmt: *Node) CodegenError!void {
        switch (stmt.kind) {

            .VarDecl, .ConstDecl => {
                const name      = if (stmt.kind == .VarDecl) stmt.data.var_decl.name       else stmt.data.const_decl.name;
                const init_expr = if (stmt.kind == .VarDecl) stmt.data.var_decl.init_expr  else stmt.data.const_decl.init_expr;
                const t = stmt.resolved_type orelse AshType{ .kind = .Unknown };
                try self.ind();
                if (t.kind == .Struct) {
                    try self.w(t.name orelse "void*");
                } else if (t.kind == .Array) {
                    try self.w(self.cTypeOfArray(t));
                } else {
                    try self.w(self.cTypeOf(t));
                }
                try self.wf(" {s} = ", .{name});
                try self.genExpr(init_expr);
                try self.w(";\n");
            },

            // x, y := func_returning_tuple()
            // Lowers to:  __Ash_f_ret __tmp_N = ash_f(...);
            //             T0 x = __tmp_N._0;
            //             T1 y = __tmp_N._1;
            .MultiVarDecl => {
                const mv = &stmt.data.multi_var_decl;
                const init_t = stmt.resolved_type orelse AshType{ .kind = .Unknown };

                if (init_t.kind == .Tuple) {
                    // Figure out the called function name to build the ret-struct type
                    const func_name: []const u8 = if (mv.init_expr.kind == .CallExpr)
                        mv.init_expr.data.call_expr.callee else "__unknown";
                    const sname = try self.retStructName(func_name);
                    defer self.allocator.free(sname);

                    // Emit: __Ash_f_ret __tmp = ash_f(...);
                    try self.ind();
                    try self.wf("{s} __mv_{s} = ", .{ sname, mv.names[0] });
                    try self.genExpr(mv.init_expr);
                    try self.w(";\n");

                    // Emit one variable per name
                    const tt = init_t.tuple_types orelse &[_]AshType{};
                    for (mv.names, 0..) |name, i| {
                        const member_t = if (i < tt.len) tt[i] else AshType{ .kind = .Unknown };
                        try self.ind();
                        try self.emitCType(member_t);
                        try self.wf(" {s} = __mv_{s}._{d};\n", .{ name, mv.names[0], i });
                    }
                } else {
                    // Not a tuple — bind all names to the single value (edge case)
                    try self.ind();
                    try self.emitCType(init_t);
                    try self.wf(" {s} = ", .{mv.names[0]});
                    try self.genExpr(mv.init_expr);
                    try self.w(";\n");
                    for (mv.names[1..]) |name| {
                        try self.ind();
                        try self.emitCType(init_t);
                        try self.wf(" {s} = {s};\n", .{ name, mv.names[0] });
                    }
                }
            },

            .AssignStmt => {
                const as = &stmt.data.assign_stmt;
                try self.ind();
                if (as.target.kind == .IndexExpr) {
                    const ie = &as.target.data.index_expr;
                    const arr_t = ie.array.resolved_type orelse AshType{ .kind = .Unknown };
                    if (arr_t.kind == .Array) {
                        try self.genExpr(ie.array);
                        try self.w("["); try self.genExpr(ie.index); try self.w("] = ");
                        try self.genExpr(as.value); try self.w(";\n");
                    } else {
                        const et = if (arr_t.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                        const fn_set = vecSetFn(et.kind);
                        try self.wf("{s}(", .{fn_set});
                        try self.genExpr(ie.array); try self.w(", ");
                        try self.genExpr(ie.index);  try self.w(", ");
                        try self.genExpr(as.value);  try self.w(");\n");
                    }
                } else {
                    try self.genExpr(as.target); try self.w(" = ");
                    try self.genExpr(as.value);  try self.w(";\n");
                }
            },

            .CompoundAssignStmt => {
                const ca = &stmt.data.compound_assign_stmt;
                try self.ind();
                try self.genExpr(ca.target);
                try self.w(if (ca.op == .AddAssign) " += " else " -= ");
                try self.genExpr(ca.value);
                try self.w(";\n");
            },

            .ExprStmt => {
                try self.ind();
                try self.genExpr(stmt.data.expr_stmt.expr);
                try self.w(";\n");
            },

            .ReturnStmt => {
                try self.ind();
                if (stmt.data.return_stmt.value) |v| {
                    // Multi-return: wrap values in the ret-struct
                    if (v.kind == .TupleExpr) {
                        try self.genTupleReturn(v);
                    } else {
                        try self.w("return ");
                        try self.genExpr(v);
                        try self.w(";\n");
                    }
                } else {
                    try self.w("return;\n");
                }
            },

            .BreakStmt    => { try self.ind(); try self.w("break;\n"); },
            .ContinueStmt => { try self.ind(); try self.w("continue;\n"); },
            .IfStmt       => try self.genIf(stmt),
            .ForRangeStmt => try self.genForRange(stmt),
            .ForEachStmt  => try self.genForEach(stmt),
            .WhileStmt    => try self.genWhile(stmt),
            .SwitchStmt   => try self.genSwitch(stmt),
            else => {},
        }
    }

    // Emit: return (__Ash_f_ret){ ._0 = a, ._1 = b };
    // We need the current function name — we walk up to find it, but since
    // codegen is linear we can track it. Simpler: use a compound literal with
    // positional initializers.
    fn genTupleReturn(self: *Codegen, tuple: *Node) CodegenError!void {
        const elems = tuple.data.tuple_expr.elements;
        // We can't easily know the ret-struct name here without threading
        // the function name down.  Use a GNU compound-literal trick: cast a
        // struct literal.  Instead, use an __attribute__-free approach:
        // emit individual tmp vars then return them — but that needs the struct
        // type name.  Simplest: just emit the struct literal by positional init.
        // Since we generated "typedef struct { T _0; T _1; } __Ash_f_ret;" we
        // rely on the caller knowing the struct.  We use a cast-free form:
        //   return (__Ash_f_ret){ a, b };
        // which works in C99+ with compound literals.
        // We don't have the function name here. Store it in a field.
        // Actually the simplest approach: since genStmt is called from
        // genBlock which is called from emitFunctionBody which knows the name,
        // we thread current_func_name through the Codegen struct.
        try self.wf("return ({s}){{ ", .{self.cur_func_ret_struct});
        for (elems, 0..) |elem, i| {
            if (i > 0) try self.w(", ");
            try self.genExpr(elem);
        }
        try self.w(" };\n");
    }

    // ── control-flow ────────────────────────────────────────────────────────

    fn genIf(self: *Codegen, stmt: *Node) CodegenError!void {
        const is = &stmt.data.if_stmt;
        try self.ind(); try self.w("if ("); try self.genExpr(is.condition); try self.w(") {\n");
        self.indent += 1; try self.genBlock(is.then_block); self.indent -= 1;
        try self.ind(); try self.w("}");
        if (is.else_block) |eb| {
            if (eb.kind == .IfStmt) {
                try self.w(" else ");
                // genIf will call ind() which would double-indent here.
                // Suppress it by temporarily zeroing indent, then restoring.
                const saved = self.indent;
                self.indent = 0;
                try self.genIf(eb);
                self.indent = saved;
                return;
            }
            try self.w(" else {\n");
            self.indent += 1; try self.genBlock(eb); self.indent -= 1;
            try self.ind(); try self.w("}");
        }
        try self.w("\n");
    }

    fn genForRange(self: *Codegen, stmt: *Node) CodegenError!void {
        const fr = &stmt.data.for_range_stmt;
        try self.ind();
        try self.w("{ int64_t __s = "); try self.genExpr(fr.start);
        try self.w("; int64_t __e = ");  try self.genExpr(fr.end);
        try self.wf("; for (int64_t {s} = __s; {s} < __e; {s}++) {{\n",
            .{ fr.var_name, fr.var_name, fr.var_name });
        self.indent += 1; try self.genBlock(fr.body); self.indent -= 1;
        try self.ind(); try self.w("} }\n");
    }

    fn genForEach(self: *Codegen, stmt: *Node) CodegenError!void {
        const fe    = &stmt.data.for_each_stmt;
        const iter_t = fe.iterable.resolved_type orelse AshType{ .kind = .Unknown };
        const elem_t = if (iter_t.elem_type) |et| et.* else AshType{ .kind = .Unknown };
        const getter  = vecGetFn(elem_t.kind);
        const elem_ct = vecElemCType(elem_t.kind);
        try self.ind();
        try self.w("{ int64_t __fe_i = 0; AshVec* __fe_v = ");
        try self.genExpr(fe.iterable);
        try self.w("; for (; __fe_i < ash_vec_len(__fe_v); __fe_i++) {\n");
        self.indent += 1;
        try self.ind();
        try self.wf("{s} {s} = {s}(__fe_v, __fe_i);\n",
            .{ elem_ct, fe.var_name, getter });
        try self.genBlock(fe.body);
        self.indent -= 1;
        try self.ind(); try self.w("} }\n");
    }

    fn genWhile(self: *Codegen, stmt: *Node) CodegenError!void {
        const ws = &stmt.data.while_stmt;
        try self.ind();
        try self.w("while ("); try self.genExpr(ws.condition); try self.w(") {\n");
        self.indent += 1; try self.genBlock(ws.body); self.indent -= 1;
        try self.ind(); try self.w("}\n");
    }

    fn genSwitch(self: *Codegen, stmt: *Node) CodegenError!void {
        const ss = &stmt.data.switch_stmt;
        const subj_t = ss.subject.resolved_type orelse AshType{ .kind = .Unknown };
        if (subj_t.kind == .String) {
            try self.genStringSwitch(stmt); return;
        }
        try self.ind();
        try self.w("switch ((int64_t)("); try self.genExpr(ss.subject); try self.w(")) {\n");
        for (ss.cases) |case| {
            if (case.value) |v| {
                try self.ind();
                try self.w("case (int64_t)("); try self.genExpr(v); try self.w("): {\n");
            } else {
                try self.ind(); try self.w("default: {\n");
            }
            self.indent += 1;
            for (case.body) |s| try self.genStmt(s);
            const has_break = case.body.len > 0 and
                case.body[case.body.len-1].kind == .BreakStmt;
            if (!has_break) { try self.ind(); try self.w("break;\n"); }
            self.indent -= 1;
            try self.ind(); try self.w("}\n");
        }
        try self.ind(); try self.w("}\n");
    }

    fn genStringSwitch(self: *Codegen, stmt: *Node) CodegenError!void {
        const ss = &stmt.data.switch_stmt;
        var first = true;
        for (ss.cases) |case| {
            try self.ind();
            if (case.value) |v| {
                if (first) { try self.w("if"); first = false; } else try self.w("else if");
                try self.w(" (strcmp("); try self.genExpr(ss.subject);
                try self.w(", "); try self.genExpr(v); try self.w(") == 0) {\n");
            } else {
                try self.w("else {\n");
            }
            self.indent += 1;
            for (case.body) |s| try self.genStmt(s);
            self.indent -= 1;
            try self.ind(); try self.w("}\n");
        }
    }

    // ── expressions ────────────────────────────────────────────────────────

    fn genExpr(self: *Codegen, expr: *Node) CodegenError!void {
        switch (expr.kind) {
            .IntLiteral    => try self.wf("INT64_C({d})", .{expr.data.int_literal.value}),
            .FloatLiteral  => try self.wf("{d}", .{expr.data.float_literal.value}),
            .BoolLiteral   => try self.w(if (expr.data.bool_literal.value) "1" else "0"),
            .StringLiteral => try self.genStringLit(expr.data.string_literal.value),
            .IdentExpr     => try self.w(expr.data.ident_expr.name),

            .FieldExpr => {
                const fe = &expr.data.field_expr;
                const obj_t = fe.object.resolved_type orelse AshType{ .kind = .Unknown };
                if (obj_t.kind == .Enum) {
                    // Enum variant: emit the #define  ASH_EnumName__Variant
                    try self.wf("ASH_{s}__{s}", .{ obj_t.name orelse "Unknown", fe.field });
                } else {
                    try self.genExpr(fe.object);
                    try self.wf(".{s}", .{fe.field});
                }
            },

            .BinaryExpr    => try self.genBinary(expr),
            .UnaryExpr => {
                const ue = &expr.data.unary_expr;
                switch (ue.op) {
                    .Neg => { try self.w("(-");  try self.genExpr(ue.operand); try self.w(")"); },
                    .Not => { try self.w("(!");  try self.genExpr(ue.operand); try self.w(")"); },
                }
            },

            .CallExpr      => try self.genCall(expr),

            .IndexExpr => {
                const ie    = &expr.data.index_expr;
                const arr_t = ie.array.resolved_type orelse AshType{ .kind = .Unknown };
                if (arr_t.kind == .Array) {
                    try self.genExpr(ie.array); try self.w("[");
                    try self.genExpr(ie.index); try self.w("]");
                } else {
                    const et = if (arr_t.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                    try self.wf("{s}(", .{vecGetFn(et.kind)});
                    try self.genExpr(ie.array); try self.w(", ");
                    try self.genExpr(ie.index); try self.w(")");
                }
            },

            .StructLiteral => {
                const sl = &expr.data.struct_literal;
                try self.wf("({s}){{", .{sl.type_name});
                for (sl.fields, 0..) |f, i| {
                    if (i > 0) try self.w(", ");
                    try self.wf(".{s} = ", .{f.name});
                    try self.genExpr(f.value);
                }
                try self.w("}");
            },

            .ArrayLiteral => {
                const t  = expr.resolved_type orelse AshType{ .kind = .Unknown };
                const et = if (t.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                try self.wf("({{ AshVec* __av = ash_vec_new();", .{});
                for (expr.data.array_literal.elements) |elem| {
                    try self.wf(" {s}(__av, ", .{vecPushFn(et.kind)});
                    try self.genExpr(elem); try self.w(");");
                }
                try self.w(" __av; })");
            },

            .FixedArrayLiteral => {
                const t  = expr.resolved_type orelse AshType{ .kind = .Unknown };
                const et = if (t.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                const ct: []const u8 = switch (et.kind) {
                    .Int    => "int64_t",
                    .Float  => "double",
                    .Bool   => "int",
                    .String => "const char*",
                    else    => "int64_t",
                };
                try self.wf("(({s}[]){{", .{ct});
                for (expr.data.fixed_array_literal.elements, 0..) |elem, i| {
                    if (i > 0) try self.w(", ");
                    try self.genExpr(elem);
                }
                try self.w("})");
            },

            else => try self.w("/*?*/"),
        }
    }

    fn genStringLit(self: *Codegen, s: []const u8) CodegenError!void {
        try self.w("\"");
        for (s) |c| switch (c) {
            '\n' => try self.w("\\n"),
            '\t' => try self.w("\\t"),
            '\r' => try self.w("\\r"),
            '"'  => try self.w("\\\""),
            '\\' => try self.w("\\\\"),
            else => try self.wf("{c}", .{c}),
        };
        try self.w("\"");
    }

    fn genBinary(self: *Codegen, expr: *Node) CodegenError!void {
        const be = &expr.data.binary_expr;
        const lt = be.left.resolved_type  orelse AshType{ .kind = .Unknown };
        const rt = be.right.resolved_type orelse AshType{ .kind = .Unknown };
        // String concatenation with +
        // Use ash_str_concat whenever EITHER operand is a String — this handles
        // chained expressions like ("Hello, " + name) + "!" where the left side
        // returns const char* from a previous ash_str_concat call.
        if (be.op == .Add and (lt.kind == .String or rt.kind == .String)) {
            try self.w("ash_str_concat(");
            try self.genExpr(be.left); try self.w(", ");
            try self.genExpr(be.right); try self.w(")");
            return;
        }
        const op_str: []const u8 = switch (be.op) {
            .Add => "+", .Sub => "-", .Mul => "*", .Div => "/", .Mod => "%",
            .Eq  => "==", .Ne => "!=", .Lt => "<", .Gt => ">", .Le => "<=", .Ge => ">=",
            .And => "&&", .Or => "||",
        };
        // Only wrap in parens for arithmetic ops (needed for precedence).
        // Comparison/logical ops don't need outer parens since genIf/genWhile add them.
        const needs_parens = switch (be.op) { .Add, .Sub, .Mul, .Div, .Mod => true, else => false };
        if (needs_parens) try self.w("(");
        try self.genExpr(be.left);
        try self.wf(" {s} ", .{op_str});
        try self.genExpr(be.right);
        if (needs_parens) try self.w(")");
    }

    fn genCall(self: *Codegen, expr: *Node) CodegenError!void {
        const ce = &expr.data.call_expr;
        const c  = ce.callee;

        // ── print ─────────────────────────────────────────────────────────
        if (std.mem.eql(u8, c, "print")) {
            if (ce.args.len == 0) { try self.w("ash_print_newline()"); return; }
            if (ce.args.len == 1) {
                try self.w("("); try self.printArg(ce.args[0]);
                try self.w(", ash_print_newline())"); return;
            }
            try self.w("(");
            for (ce.args, 0..) |arg, i| {
                if (i > 0) try self.w(", ash_print_string(\" \"), ");
                try self.printArg(arg);
            }
            try self.w(", ash_print_newline())"); return;
        }

        // ── vec builtins ──────────────────────────────────────────────────
        if (std.mem.eql(u8, c, "vec_new"))  { try self.w("ash_vec_new()"); return; }
        if (std.mem.eql(u8, c, "vec_len"))  { try self.w("ash_vec_len(");  try self.argList(ce.args); try self.w(")"); return; }
        if (std.mem.eql(u8, c, "vec_clear")){ try self.w("ash_vec_clear(");try self.argList(ce.args); try self.w(")"); return; }
        if (std.mem.eql(u8, c, "len")) {
            if (ce.args.len == 1) {
                const at = ce.args[0].resolved_type orelse AshType{ .kind = .Unknown };
                if (at.kind == .Array) {
                    // Fixed array — emit the compile-time size constant.
                    // array_size is stored on the type by the semantic analyzer.
                    if (at.array_size) |n| {
                        try self.wf("INT64_C({d})", .{n}); return;
                    }
                    // Fallback: count from literal if possible
                    if (ce.args[0].kind == .FixedArrayLiteral) {
                        const n = ce.args[0].data.fixed_array_literal.elements.len;
                        try self.wf("INT64_C({d})", .{n}); return;
                    }
                    // Last resort: should not happen after semantic pass
                    try self.w("INT64_C(0)"); return;
                }
            }
            try self.w("ash_vec_len("); try self.argList(ce.args); try self.w(")"); return;
        }
        if (std.mem.eql(u8, c, "push")) {
            if (ce.args.len == 2) {
                const et = ce.args[1].resolved_type orelse AshType{ .kind = .Unknown };
                try self.wf("{s}(", .{vecPushFn(et.kind)});
                try self.argList(ce.args); try self.w(")");
            }
            return;
        }
        if (std.mem.eql(u8, c, "pop")) {
            if (ce.args.len == 1) {
                const vt = ce.args[0].resolved_type orelse AshType{ .kind = .Unknown };
                const et = if (vt.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                try self.wf("{s}(", .{vecPopFn(et.kind)});
                try self.argList(ce.args); try self.w(")");
            }
            return;
        }
        if (std.mem.eql(u8, c, "vec_get")) {
            if (ce.args.len == 2) {
                const vt = ce.args[0].resolved_type orelse AshType{ .kind = .Unknown };
                const et = if (vt.elem_type) |e| e.* else AshType{ .kind = .Unknown };
                try self.wf("{s}(", .{vecGetFn(et.kind)});
                try self.argList(ce.args); try self.w(")");
            }
            return;
        }
        if (std.mem.eql(u8, c, "vec_contains")) {
            if (ce.args.len == 2) {
                const et = ce.args[1].resolved_type orelse AshType{ .kind = .Unknown };
                const fn_name = if (et.kind == .String) "ash_vec_contains_str" else "ash_vec_contains_int";
                try self.wf("{s}(", .{fn_name}); try self.argList(ce.args); try self.w(")");
            }
            return;
        }

        // ── string ────────────────────────────────────────────────────────
        const str_map = .{
            .{ "str_len",     "ash_str_len" },
            .{ "str_upper",   "ash_str_upper" },
            .{ "str_lower",   "ash_str_lower" },
            .{ "str_concat",  "ash_str_concat" },
            .{ "str_slice",   "ash_str_slice" },
            .{ "str_contains","ash_str_contains" },
            .{ "parse_int",   "ash_parse_int" },
            .{ "parse_float", "ash_parse_float" },
        };
        inline for (str_map) |kv| {
            if (std.mem.eql(u8, c, kv[0])) {
                try self.wf("{s}(", .{kv[1]}); try self.argList(ce.args); try self.w(")"); return;
            }
        }
        if (std.mem.eql(u8, c, "str")) {
            if (ce.args.len == 1) {
                const at = ce.args[0].resolved_type orelse AshType{ .kind = .Unknown };
                if (at.kind == .Float) {
                    try self.w("ash_str_float("); try self.argList(ce.args); try self.w(")");
                } else {
                    try self.w("ash_str_int((int64_t)("); try self.argList(ce.args); try self.w("))");
                }
            }
            return;
        }

        // ── math ──────────────────────────────────────────────────────────
        const math_map = .{
            .{ "sqrt",  "ash_math_sqrt"  },
            .{ "pow",   "ash_math_pow"   },
            .{ "floor", "ash_math_floor" },
            .{ "ceil",  "ash_math_ceil"  },
            .{ "round", "ash_math_round" },
            .{ "sin",   "ash_math_sin"   },
            .{ "cos",   "ash_math_cos"   },
            .{ "tan",   "ash_math_tan"   },
            .{ "log",   "ash_math_log"   },
            .{ "log2",  "ash_math_log2"  },
        };
        inline for (math_map) |kv| {
            if (std.mem.eql(u8, c, kv[0])) {
                try self.wf("{s}(", .{kv[1]}); try self.argList(ce.args); try self.w(")"); return;
            }
        }
        if (std.mem.eql(u8, c, "abs")) {
            const at = if (ce.args.len > 0) ce.args[0].resolved_type orelse AshType{ .kind = .Unknown }
                       else AshType{ .kind = .Unknown };
            if (at.kind == .Float) try self.w("ash_math_abs_float(") else try self.w("ash_math_abs_int(");
            try self.argList(ce.args); try self.w(")"); return;
        }
        if (std.mem.eql(u8, c, "min")) {
            const at = if (ce.args.len > 0) ce.args[0].resolved_type orelse AshType{ .kind = .Unknown }
                       else AshType{ .kind = .Unknown };
            if (at.kind == .Float) try self.w("ash_math_min_float(") else try self.w("ash_math_min_int(");
            try self.argList(ce.args); try self.w(")"); return;
        }
        if (std.mem.eql(u8, c, "max")) {
            const at = if (ce.args.len > 0) ce.args[0].resolved_type orelse AshType{ .kind = .Unknown }
                       else AshType{ .kind = .Unknown };
            if (at.kind == .Float) try self.w("ash_math_max_float(") else try self.w("ash_math_max_int(");
            try self.argList(ce.args); try self.w(")"); return;
        }
        if (std.mem.eql(u8, c, "clamp")) {
            try self.w("ash_math_clamp_int("); try self.argList(ce.args); try self.w(")"); return;
        }

        // ── io ────────────────────────────────────────────────────────────
        if (std.mem.eql(u8, c, "input") or std.mem.eql(u8, c, "io.input")) {
            try self.w("ash_io_input("); try self.argList(ce.args); try self.w(")"); return;
        }
        if (std.mem.eql(u8, c, "read_file"))  { try self.w("ash_io_read_file(");  try self.argList(ce.args); try self.w(")"); return; }
        if (std.mem.eql(u8, c, "write_file")) { try self.w("ash_io_write_file("); try self.argList(ce.args); try self.w(")"); return; }

        // ── os ────────────────────────────────────────────────────────────
        if (std.mem.eql(u8, c, "exit"))   { try self.w("ash_os_exit(");   try self.argList(ce.args); try self.w(")"); return; }
        if (std.mem.eql(u8, c, "getenv")) { try self.w("ash_os_getenv("); try self.argList(ce.args); try self.w(")"); return; }
        if (std.mem.eql(u8, c, "argc"))   { try self.w("ash_os_argc()"); return; }
        if (std.mem.eql(u8, c, "argv"))   { try self.w("ash_os_argv("); try self.argList(ce.args); try self.w(")"); return; }

        // ── user function call ────────────────────────────────────────────
        // All user functions are prefixed with ash_ to avoid C name collisions.
        try self.wf("ash_{s}(", .{c});
        try self.argList(ce.args);
        try self.w(")");
    }

    fn argList(self: *Codegen, args: []*Node) CodegenError!void {
        for (args, 0..) |arg, i| {
            if (i > 0) try self.w(", ");
            try self.genExpr(arg);
        }
    }

    fn printArg(self: *Codegen, arg: *Node) CodegenError!void {
        const t = arg.resolved_type orelse AshType{ .kind = .Unknown };
        const fn_name: []const u8 = switch (t.kind) {
            .Int    => "ash_print_int",
            .Float  => "ash_print_float",
            .Bool   => "ash_print_bool",
            .String => "ash_print_string",
            else => blk: {
                // Infer from literal kind or call name
                switch (arg.kind) {
                    .IntLiteral    => break :blk "ash_print_int",
                    .FloatLiteral  => break :blk "ash_print_float",
                    .StringLiteral => break :blk "ash_print_string",
                    .BoolLiteral   => break :blk "ash_print_bool",
                    .CallExpr => {
                        const name = arg.data.call_expr.callee;
                        if (isIntFn(name))    break :blk "ash_print_int";
                        if (isFloatFn(name))  break :blk "ash_print_float";
                        if (isStringFn(name)) break :blk "ash_print_string";
                        break :blk "ash_print_int";
                    },
                    else => break :blk "ash_print_int",
                }
            },
        };
        try self.wf("{s}(", .{fn_name});
        try self.genExpr(arg);
        try self.w(")");
    }

    // ── vec helper name tables ──────────────────────────────────────────────

    fn vecPushFn(kind: TypeKind) []const u8 {
        return switch (kind) {
            .Float  => "ash_vec_push_float",
            .String => "ash_vec_push_str",
            .Bool   => "ash_vec_push_bool",
            else    => "ash_vec_push_int",
        };
    }
    fn vecPopFn(kind: TypeKind) []const u8 {
        return switch (kind) {
            .Float  => "ash_vec_pop_float",
            .String => "ash_vec_pop_str",
            else    => "ash_vec_pop_int",
        };
    }
    fn vecGetFn(kind: TypeKind) []const u8 {
        return switch (kind) {
            .Float  => "ash_vec_get_float",
            .String => "ash_vec_get_str",
            .Bool   => "ash_vec_get_bool",
            else    => "ash_vec_get_int",
        };
    }
    fn vecSetFn(kind: TypeKind) []const u8 {
        return switch (kind) {
            .Float  => "ash_vec_set_float",
            .String => "ash_vec_set_str",
            .Bool   => "ash_vec_set_bool",
            else    => "ash_vec_set_int",
        };
    }
    fn vecElemCType(kind: TypeKind) []const u8 {
        return switch (kind) {
            .Float  => "double",
            .String => "const char*",
            .Bool   => "int",
            else    => "int64_t",
        };
    }

    // ── print type inference helpers ────────────────────────────────────────

    fn isIntFn(name: []const u8) bool {
        const fns = [_][]const u8{ "abs","min","max","clamp","str_len","parse_int","len","argc","vec_len" };
        for (fns) |f| if (std.mem.eql(u8, name, f)) return true;
        return false;
    }
    fn isFloatFn(name: []const u8) bool {
        const fns = [_][]const u8{ "sqrt","pow","floor","ceil","round","sin","cos","tan","log","log2","parse_float" };
        for (fns) |f| if (std.mem.eql(u8, name, f)) return true;
        return false;
    }
    fn isStringFn(name: []const u8) bool {
        const fns = [_][]const u8{ "str","str_concat","str_upper","str_lower","str_slice","input","read_file","getenv","argv" };
        for (fns) |f| if (std.mem.eql(u8, name, f)) return true;
        return false;
    }
};
